#!/usr/bin/env bash
# Generate /etc/fstab on the target using filesystem UUIDs (never /dev/sdX).
#
# Immutable squashfs root:
#   /boot  rw   (GRUB, kernel, initrd, root-<ver>.squashfs image)
#   /data  rw   (overlay upperdir + persistent application state)
#   /tmp   tmpfs
# There is no / or /var entry: live-boot mounts the overlay root itself inside
# the initramfs.
#
# Sets globals BOOT_UUID and DATA_UUID (also used by grub-install.sh).

write_fstab() {
    BOOT_UUID="$(fs_uuid "$BOOT_PART")"
    DATA_UUID="$(fs_uuid "$DATA_PART")"
    [ -n "$BOOT_UUID" ] || die "Could not read UUID of $BOOT_PART"
    [ -n "$DATA_UUID" ] || die "Could not read UUID of $DATA_PART"

    log "Writing UUID-based /etc/fstab"
    cat > "$TARGET_MNT/etc/fstab" <<EOF
# RetroBox appliance — generated by install-retropc.sh. Do not hand-edit device
# names; entries are keyed by filesystem UUID.

UUID=$BOOT_UUID  /boot  ext4  rw,nosuid,nodev,noatime,errors=remount-ro  0 2
UUID=$DATA_UUID  /data  ext4  rw,nosuid,nodev,noatime                   0 2
tmpfs            /tmp   tmpfs rw,nosuid,nodev,noatime,mode=1777         0 0
EOF
    ok "fstab written (boot UUID=$BOOT_UUID, data UUID=$DATA_UUID)"
}
