#!/usr/bin/env bash
# Generate /etc/fstab on the target using filesystem UUIDs (never /dev/sdX).
#
# Runtime filesystem layout:
#   /          rw   (the installed system partition)
#   /boot/efi  vfat (EFI System Partition, GRUB-EFI)
#   /data      rw   (mutable application + system state)
#   /tmp       tmpfs
#   /var       overlay with the writable upperdir on /data, so logs, Samba state,
#              DHCP leases, and ALSA state persist without a writable root.
# SSH host keys and machine-id are generated at install time into the image.
#
# Sets globals ROOT_UUID, ESP_UUID, and DATA_UUID (also used by grub-install.sh).

write_fstab() {
    ROOT_UUID="$(fs_uuid "$ROOT_PART")"
    ESP_UUID="$(fs_uuid "$ESP_PART")"
    DATA_UUID="$(fs_uuid "$DATA_PART")"
    [ -n "$ROOT_UUID" ] || die "Could not read UUID of $ROOT_PART"
    [ -n "$ESP_UUID" ] || die "Could not read UUID of $ESP_PART"
    [ -n "$DATA_UUID" ] || die "Could not read UUID of $DATA_PART"

    log "Writing UUID-based /etc/fstab"
    cat > "$TARGET_MNT/etc/fstab" <<EOF
# RetroBox appliance — generated by install-retropc.sh. Do not hand-edit device
# names; entries are keyed by filesystem UUID.

# Writable OS root.
UUID=$ROOT_UUID  /      ext4      rw,errors=remount-ro                          0 1

# EFI System Partition (GRUB-EFI lives here). fsck pass 0: an ESP is written
# only by grub-install at install time, and fsck.vfat would have to exist in the
# image for a nonzero pass to succeed at boot.
UUID=$ESP_UUID  /boot/efi  vfat  umask=0077,nosuid,nodev,noexec                 0 0

# Mutable application + system-overlay state.
UUID=$DATA_UUID  /data  ext4      rw,nosuid,nodev,noatime                       0 2

# Volatile scratch.
tmpfs            /tmp   tmpfs     rw,nosuid,nodev,noatime,mode=1777             0 0

# /var is part of the writable system root.
EOF
    ok "fstab written (root UUID=$ROOT_UUID, ESP UUID=$ESP_UUID, data UUID=$DATA_UUID)"
}
