#!/usr/bin/env bash
# Install GRUB in UEFI mode onto the INTERNAL target disk (never the USB): the
# GRUB-EFI binary goes into the ESP mounted at /boot/efi (no MBR write), with a
# hidden appliance menu at 1280x960 and a recovery entry that skips the
# fullscreen VM path.
#
# Consumes globals: TARGET_DISK, ROOT_UUID, ESP_UUID.

install_bootloader() {
    _write_grub_defaults
    _write_recovery_entry
    log "Installing GRUB (x86_64-efi) to ESP on $TARGET_DISK"
    # Do not silence output: grub's own error is the useful diagnostic, and on
    # failure die() drops to a recovery shell instead of looping.
    in_target grub-install --target=x86_64-efi --efi-directory=/boot/efi \
        --bootloader-id=RetroBox --recheck \
        || die "grub-install failed for $TARGET_DISK (see output above)"
    log "Generating grub.cfg (UUID root)"
    in_target update-grub || die "update-grub failed (see output above)"

    # grub-common.service records a successful boot by writing grubenv, which
    # fails on our read-only root. Mask it so it doesn't show up as a failed unit.
    in_target systemctl mask grub-common.service >/dev/null 2>&1 \
        || warn "could not mask grub-common.service"

    # Silence GRUB's "Loading Linux .../Loading initial ramdisk ..." text so the
    # appliance boots straight into the Plymouth splash. (Regenerated if the
    # kernel is updated with update-grub; the immutable-image path in #43 avoids
    # that entirely.)
    sed -i '/^[[:space:]]*echo[[:space:]].*[Ll]oading/d' "$TARGET_MNT/boot/grub/grub.cfg" 2>/dev/null || true

    ok "GRUB installed to ESP on $TARGET_DISK (root UUID=$ROOT_UUID, ESP UUID=$ESP_UUID)"
}

# Kernel version string (e.g. 6.12.0-amd64) of the newest kernel in the target.
_target_kver() {
    in_target sh -c 'ls -1 /boot/vmlinuz-* 2>/dev/null | sort -V | tail -n1 | sed "s|.*/vmlinuz-||"'
}

_write_grub_defaults() {
    cat > "$TARGET_MNT/etc/default/grub" <<'EOF'
# RetroBox appliance GRUB defaults — generated by install-retropc.sh.
GRUB_DISTRIBUTOR="RetroBox"
# Hidden, near-instant menu for appliance boot; hold SHIFT (or ESC) to reveal it.
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=1
# Root is read-only, so grub-common.service cannot clear the "recordfail" flag
# in grubenv. Keep the timeout at 0 so a stuck flag never shows a menu or delay.
GRUB_RECORDFAIL_TIMEOUT=0
# Quiet boot with the Plymouth splash. Force the console/framebuffer to
# 1280x960@60 via the kernel `video=` param: GRUB_GFXMODE alone only sets the
# GRUB menu mode; once the KMS driver (i915) loads it would otherwise switch to
# the monitor's native resolution.
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash loglevel=3 rd.udev.log_level=3"
GRUB_CMDLINE_LINUX="video=1280x960@60"
GRUB_GFXMODE=1280x960x32
GRUB_GFXPAYLOAD_LINUX=keep
# Single-purpose appliance: no other OSes to probe, no stock recovery submenu
# (a tailored recovery entry is added via /etc/grub.d/40_custom).
GRUB_DISABLE_OS_PROBER=true
GRUB_DISABLE_RECOVERY=true
EOF
}

_write_recovery_entry() {
    local kver
    kver="$(_target_kver)"
    if [ -z "$kver" ]; then
        warn "No kernel found in target /boot; skipping custom recovery entry."
        return
    fi
    cat > "$TARGET_MNT/etc/grub.d/40_custom" <<EOF
#!/bin/sh
exec tail -n +3 "\$0"
# RetroBox recovery: boots the appliance normally but appends retropc.norun=1,
# which retrobox-boot.service honors to stay out of the fullscreen VM path and
# leave a maintenance login on tty1.
menuentry 'RetroBox — recovery (maintenance, no fullscreen VM)' --class recovery {
    insmod part_gpt
    insmod ext2
    search --no-floppy --fs-uuid --set=root $ROOT_UUID
    echo 'Loading RetroBox recovery...'
    linux /boot/vmlinuz-$kver root=UUID=$ROOT_UUID ro retropc.norun=1 video=1280x960@60
    initrd /boot/initrd.img-$kver
}
EOF
    chmod 0755 "$TARGET_MNT/etc/grub.d/40_custom"
}