#!/usr/bin/env bash
# Install GRUB in BIOS/legacy MBR mode onto the INTERNAL target disk (never the
# USB), with a hidden appliance menu at 1280x960 and a recovery entry that skips
# the fullscreen VM path.
#
# Consumes globals: TARGET_DISK, BOOT_UUID, BOOT_KVER.

install_bootloader() {
    _write_grub_defaults
    _write_recovery_entry
    log "Installing GRUB (i386-pc) to $TARGET_DISK MBR"
    # Do not silence output: grub's own error is the useful diagnostic, and on
    # failure die() drops to a recovery shell instead of looping.
    in_target grub-install --target=i386-pc --recheck --no-floppy "$TARGET_DISK" \
        || die "grub-install failed for $TARGET_DISK (see output above)"
    log "Generating grub.cfg (UUID boot)"
    in_target update-grub || die "update-grub failed (see output above)"

    # Silence GRUB's "Loading Linux .../Loading initial ramdisk ..." text so the
    # appliance boots straight into the Plymouth splash.
    sed -i '/^[[:space:]]*echo[[:space:]].*[Ll]oading/d' "$TARGET_MNT/boot/grub/grub.cfg" 2>/dev/null || true

    ok "GRUB installed to $TARGET_DISK (boot UUID=$BOOT_UUID)"
}

# Kernel version string (e.g. 6.12.0-amd64) for the boot entry. Prefer the
# version recorded by stage_image(); fall back to the newest kernel staged in
# the target /boot.
_target_kver() {
    if [ -n "$BOOT_KVER" ]; then
        printf '%s\n' "$BOOT_KVER"
        return 0
    fi
    in_target sh -c 'ls -1 /boot/vmlinuz-* 2>/dev/null | sort -V | tail -n1 | sed "s|.*/vmlinuz-||"'
}

_write_grub_defaults() {
    cat > "$TARGET_MNT/etc/default/grub" <<EOF
# RetroBox appliance GRUB defaults — generated by install-retropc.sh.
GRUB_DISTRIBUTOR="RetroBox"
# Hidden, near-instant menu for appliance boot; hold SHIFT (or ESC) to reveal it.
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=1
# Immutable squashfs root assembled by live-boot in the initramfs: root= points
# at the /boot partition by UUID, persistence-label tells live-boot where the
# overlay upper/work dirs live, union=overlay selects overlayfs. Quiet boot with
# the Plymouth splash; video= forces the console/framebuffer to 1280x960@60
# (GRUB_GFXMODE alone only sets the GRUB menu mode; once the KMS driver (i915)
# loads it would otherwise switch to the monitor's native resolution).
GRUB_CMDLINE_LINUX="root=UUID=$BOOT_UUID boot=live components persistence persistence-label=retropc-data union=overlay quiet video=1280x960@60"
GRUB_GFXMODE=1280x960x32
GRUB_GFXPAYLOAD_LINUX=keep
# Single-purpose appliance: no other OSes to probe, no stock recovery submenu
# (a tailored recovery entry is added via /etc/grub.d/40_custom).
GRUB_DISABLE_OS_PROBER=true
GRUB_DISABLE_RECOVERY=true
EOF
}

_write_recovery_entry() {
    local kver
    kver="$(_target_kver)"
    if [ -z "$kver" ]; then
        warn "No kernel found in target /boot; skipping custom recovery entry."
        return
    fi
    cat > "$TARGET_MNT/etc/grub.d/40_custom" <<EOF
#!/bin/sh
exec tail -n +3 "\$0"
# RetroBox recovery: boots the appliance normally but appends retropc.norun=1,
# which retrobox-boot.service honors to stay out of the fullscreen VM path and
# leave a maintenance login on tty1.
menuentry 'RetroBox — recovery (maintenance, no fullscreen VM)' --class recovery {
    insmod part_msdos
    insmod ext2
    search --no-floppy --fs-uuid --set=root $BOOT_UUID
    echo 'Loading RetroBox recovery...'
    linux /boot/vmlinuz-$kver root=UUID=$BOOT_UUID boot=live components persistence persistence-label=retropc-data union=overlay quiet video=1280x960@60 retropc.norun=1
    initrd /boot/initrd.img-$kver
}
EOF
    chmod 0755 "$TARGET_MNT/etc/grub.d/40_custom"
}
