#!/usr/bin/env bash
# Detect appliance hardware, write the RetroBox daemon/hardware config into the
# target, and record an install report. Detection never aborts the install: an
# absent device yields a clearly-marked placeholder. See hardware-detect.md.
#
# Consumes globals: TARGET_DISK, ROOT_UUID, DATA_UUID, RETROBOX_STATUS, BOX86_STATUS.

detect_cdrom() {
    local d
    for d in /dev/disk/by-id/*cd* /dev/disk/by-id/*CD* \
             /dev/disk/by-id/*dvd* /dev/disk/by-id/*DVD*; do
        [ -e "$d" ] || continue
        CDROM_DEVICE="$d"; CDROM_STATUS="DETECTED"; return
    done
    if [ -b /dev/sr0 ];   then CDROM_DEVICE="/dev/sr0";   CDROM_STATUS="DETECTED"; return; fi
    if [ -e /dev/cdrom ]; then CDROM_DEVICE="/dev/cdrom"; CDROM_STATUS="DETECTED"; return; fi
    CDROM_DEVICE="/dev/sr0"; CDROM_STATUS="NOT_DETECTED"
}

detect_serial() {
    SERIAL_BAUD="${RETROPC_SERIAL_BAUD:-115200}"
    local d
    for d in /dev/serial/by-id/*; do
        [ -e "$d" ] || continue
        SERIAL_DEVICE="$d"; SERIAL_STATUS="DETECTED"; return
    done
    for d in /dev/ttyUSB* /dev/ttyACM*; do
        [ -e "$d" ] || continue
        SERIAL_DEVICE="$d"; SERIAL_STATUS="DETECTED_FALLBACK"; return
    done
    SERIAL_DEVICE="/dev/ttyUSB0"; SERIAL_STATUS="NOT_DETECTED"
}

write_hardware_config() {
    mkdir -p "$TARGET_MNT/etc/retrobox"

    # Consumed by retrobox-daemon.service.
    cat > "$TARGET_MNT/etc/retrobox/daemon.env" <<EOF
# RetroBox daemon environment — generated by install-retropc.sh.
# ESP8266/NodeMCU serial controller ($SERIAL_STATUS). Edit if the device path
# changes; prefer a stable /dev/serial/by-id/* path.
SERIAL_DEVICE=$SERIAL_DEVICE
SERIAL_BAUD=$SERIAL_BAUD
FLOPPY_CONTROL_SOCKET=/run/retrobox/86box-floppy.sock
EOF

    # Consumed by the 86Box / RetroBox VM layer for physical CD-ROM passthrough.
    cat > "$TARGET_MNT/etc/retrobox/hardware.env" <<EOF
# Physical hardware paths — generated by install-retropc.sh.
# 86Box Pentium profile CD-ROM passthrough host device ($CDROM_STATUS).
CDROM_DEVICE=$CDROM_DEVICE
EOF
}

write_install_report() {
    local by_id report="$TARGET_MNT/data/retrobox/install-report.txt"
    by_id="$(ls -l /dev/disk/by-id/ 2>/dev/null | awk -v d="$(basename "$TARGET_DISK")" \
        '$NF ~ ("/"d"$") {print "/dev/disk/by-id/"$(NF-2); exit}')"
    mkdir -p "$TARGET_MNT/data/retrobox"
    cat > "$report" <<EOF
generated=install-retropc.sh
target.disk=$TARGET_DISK
target.disk.by_id=${by_id:-unknown}
target.root.uuid=$ROOT_UUID
target.data.uuid=$DATA_UUID
cdrom.device=$CDROM_DEVICE
cdrom.status=$CDROM_STATUS
serial.device=$SERIAL_DEVICE
serial.baud=$SERIAL_BAUD
serial.status=$SERIAL_STATUS
retrobox.binary=$RETROBOX_STATUS
box86.appimage=$BOX86_STATUS
EOF
}

detect_and_record_hardware() {
    log "Detecting CD-ROM and ESP8266 serial devices"
    detect_cdrom
    detect_serial
    log "CD-ROM: $CDROM_DEVICE ($CDROM_STATUS)"
    log "Serial: $SERIAL_DEVICE @ ${SERIAL_BAUD} ($SERIAL_STATUS)"
    write_hardware_config
    write_install_report
    ok "Hardware config + install report written"
}
